name: flutter_debug_overlay
description: "A professional debug overlay widget for QA testing with network logging, JSON viewer, and filtering."
version: 1.0.0
homepage: https://github.com/yourusername/flutter_debug_overlay
repository: https://github.com/yourusername/flutter_debug_overlay
issue_tracker: https://github.com/yourusername/flutter_debug_overlay/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Flexible integrations - works with existing versions
  dio: ^5.9.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
